### ISSUE TITLE
Installation issue with ecf-rs-distribution-rosgi and karaf

### ISSUE THREAD

**Issue by tvogel8570** [ECF/Websockets#1]
I am having an issue with installing ecf-rs-distribution-rosgi into karaf.  Karaf fails to add it with the error **Unable to resolve ch.ethz.iks.r_osgi.remote/1.2.201.v20191025-0020**.  This is into a fresh install of karaf 4.2.6 using ecf-rs-distribution-rosgi 3.14.6.  Below is a full transcript of the attempt.

```
Apache Karaf (4.2.6)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit 'system:shutdown' to shutdown Karaf.
Hit '<ctrl-d>' or type 'logout' to disconnect shell from current session.

karaf@root()> list
START LEVEL 100 , List Threshold: 50
ID │ State  │ Lvl │ Version │ Name
───┼────────┼─────┼─────────┼──────────────────────────
23 │ Active │  80 │ 4.2.6   │ Apache Karaf :: OSGi Services :: Event
karaf@root()>  repo-add ecf
>
Adding feature url http://download.eclipse.org/rt/ecf/RELEASE/site.p2/karaf-features.xml
karaf@root()>  feature:install -v ecf-rs-sdk
Adding features: ecf-rs-sdk/[3.14.6,3.14.6]
karaf@root()>  feature:install -v ecf-rs-distribution-rosgi
>
Adding features: ecf-rs-distribution-rosgi/[3.14.6,3.14.6]
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=ecf-rs-distribution-rosgi; type=karaf.feature; version="[3.14.6,3.14.6]"; filter:="(&(osgi.identity=ecf-rs-distribution-rosgi)(type=karaf.feature)(version>=3.14.6)(version<=3.14.6))" [caused by: Unable to resolve ecf-rs-distribution-rosgi/3.14.6: missing requirement [ecf-rs-distribution-rosgi/3.14.6] osgi.identity; osgi.identity=ch.ethz.iks.r_osgi.remote; type=osgi.bundle; version="[1.2.201.v20191025-0020,1.2.201.v20191025-0020]"; resolution:=mandatory [caused by: Unable to resolve ch.ethz.iks.r_osgi.remote/1.2.201.v20191025-0020: missing requirement [ch.ethz.iks.r_osgi.remote/1.2.201.v20191025-0020] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.objectweb.asm)(version>=5.0.1)(!(version>=8.0.0)))"]]
karaf@root()>
```

**Comment by scottslewis** [comment]
Hi Tim.

I'll debug this.   Sounds like maybe a typo in feature.xml but I'l verify.

Thanks.

**Comment by scottslewis** [comment]
Good news and Bad News.

Bad News is:  This is a bug in the ECF sdk karaf features so it will take a new ECF release (3.14.7) to completely fix the issue.

Good News:   It's easy to work around.  Before installing ecf-rs-distribution-rosgi simply enter from karaf console:

karaf@root()> bundle:install mvn:org.eclipse.ecf/org.objectweb.asm  

This will install the ASM dependency and then the install of ecf-rs-distribution-rosgi feature will install.

Alternatively, I've created a Karaf feature for the websockets rosgi extension available here:

https://raw.githubusercontent.com/ECF/ROSGI-Websockets-Provider/master/build/karaf-features.xml

This repo includes the ECF SDK repo, and has a single feature  ecf-rs-distribution-rosgi-ws that will install everything (ecf sdk, rosgi, rosgi ws support) so to install via this repo all that's necessary is:

karaf@root()>feature:repo-add https://raw.githubusercontent.com/ECF/ROSGI-Websockets-Provider/master/build/karaf-features.xml
karaf@root()>feature:install -v ecf-rs-distribution-rosgi-ws

I'll also apply the fix to ECF SDK so it's available in next release (3.14.7).

**Comment by tvogel8570** [comment]
Thanks for the quick response and workaround!  Glad to see ECF is continuing to not only be supported but enhanced!

**Comment by scottslewis** [comment]
Hi Tim.  You are welcome.  

I'm engaged with contract work now, so don't get a lot of time, but I have been active adding support for (e.g.) Python, Hazelcast, Dubbo-based distribution and etcd discovery providers...all on github.   I've also been adding a lot of support for using bndtools (rather than PDE)....e.g. a bndtools remote services workspace with templates, etc.

It's getting pretty fast and relatively easy to do so...and I'm trying to get others to help out with enhancements when possible.   Any public promotion/supportive words would be appreciated...if you get the chance!   Our biggest hurdle continues to be visibility!

**Comment by tvogel8570** [comment]
Scott,
	Are the plugins in this karaf feature available for Eclipse from a p2 repo?  I’m specifically looking for ch.ethz.iks.r_osgi.transport.http_1.1.0.201509011032.jar and java_websocket_1.0.0.201503011507.jar (or a more recent version) to include on the client side.
Tim

**Comment by scottslewis** [comment]
Hi Tim,

Yes...more recent versions of both those bundles are available within 
the feature defined here:

https://github.com/ECF/ROSGI-Websockets-Provider/blob/master/build/karaf-features.xml

I've modified this karaf-features so that if you have already installed 
3.14.7 (as we discussed...i.e. after removing the repository references 
toward end) you can do:

karaf>feature:repo-add 
https://raw.githubusercontent.com/ECF/ROSGI-Websockets-Provider/master/build/karaf-features.xml

karaf>feature:install -v ecf-rs-distribution-rosgi-ws

To install these two bundles.

Scott

**Comment by tvogel8570** [comment]
Scott,
               Sorry I wasn’t clear.  Are they available in a p2 repo for including in an RCP client already or should I make my own local p2 repo?
Tim

**Comment by scottslewis** [comment]
Hi Tim,

There is a p2 repo for this feature here: 
https://raw.githubusercontent.com/ECF/ROSGI-Websockets-Provider/master/build

Need to uncheck 'Group items by category'

Scott

**Comment by tvogel8570** [comment]
Thanks that’s just what I needed.
